import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex'>
        <div className="">
          <Sidebar />
        </div>
        <div className="p-4 bg-gray-100 flex-grow overflow-y-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
